# MongoDB Cloud Connection (Atlas)
spring.data.mongodb.uri=mongodb+srv://riyasharma2864_db_user:bI5hVimbk8OvhRVk@cluster0.hfwfpvi.mongodb.net/inventory_db?retryWrites=true&w=majority&appName=Cluster0

# Server Port (Keep this if you already had it)
server.port=8080

# Logging for Debugging (Optional but helpful for MongoDB)
logging.level.org.springframework.data.mongodb=DEBUG