# MongoDB Cloud Connection (Secure Variable)
# This will be provided by Render.com or your local ENV
spring.data.mongodb.uri=${MONGODB_URI}

# Server Configuration
server.port=8080

# Logging for Debugging
# Displays MongoDB queries in the console to help you track "Write-errors"
logging.level.org.springframework.data.mongodb=DEBUG